---
# Ansible playbook to update the OS of (Ubuntu) VMR perf testing hosts...
- hosts: subhost1, subhost2, subhost3, subhost4, pubhost1, pubhost2, pubhost3, pubhost4, pubhost5
  remote_user: "{{ user }}"
  vars:
    #main setup variables
    user: 'ubuntu' #default user to use for logging in to hosts
  ######################
  ######## MAIN ########
  ######################
  tasks:
  - name: 'update'
    shell:  "sudo apt-get update; sudo apt-get -y upgrade; sudo apt-get -y dist-upgrade; sudo apt-get -y autoremove; sudo apt-get clean "
    when: "'{{ item.groups }}' in group_names "
    args:
      executable: "/bin/bash"
    register: "update"
    with_items:
      - { groups: 'subhost1' }
      - { groups: 'subhost2' }
      - { groups: 'subhost3' }
      - { groups: 'subhost4' }
      - { groups: 'pubhost1' }
      - { groups: 'pubhost2' }
      - { groups: 'pubhost3' }
      - { groups: 'pubhost4' }
      - { groups: 'pubhost5' }

  - name: 'display update results'
    debug: msg="{{ update.results| map(attribute='stdout') | list }}"
