---
- hosts: subhost, pubhost
  remote_user: "{{ sshuser }}"
  vars_files:
    - ../config/credentials.yaml
  vars:
    #main setup variables - can be overriden by calling script
    # sshuser is loaded from config/credentials.yaml (written by setup.sh); default: perfharness
    script_path: '/home/{{ sshuser }}/pubSubTools'

    #variables controlling the test type - most of these are being overwritten by calling scripts
    runlength: 120 #default run length for each test
    mt: persistent #default message type: direct, nonpersistent or persistent
    msg_size: 1024 # default message payload size
    #how many individual consumers on each topic:
    sdk_fanout: 1 #default fanout number
    sdk_fanout_calc: "{{ [sdk_fanout, 1] | max }}" #for calculations avoiding div by zero
    #how many hosts to run publishers and subscribers on:
    parallel_hosts: 1 #default publisher and consumer hosts
    #set the overall target msg rate you want to achieve (incl fanout):
    target_msg_rate: 0 #default message rate to achieve
    #more or less constant and calculated values...
    sdk_consumer_threads: 1 #default=1, increase, if you need some load balancing
    
    ##section for calculating values based on input variables ##
    HOST_COUNT: "{{ parallel_hosts }}"
    HOST_COUNT_calc: "{{ [HOST_COUNT, 1] | max }}" #for calculations avoiding div by zero
    msg_rate: "{{ (target_msg_rate / (HOST_COUNT_calc | int) / (sdk_fanout_calc | int)) | int }}" # rate per publisher host
    #set sdk_publishers equal to the number of cores on the test hosts:
    sdk_publishers: 4 #default number of clients on each publisher hosts
    #set actual number of publishers to the lower of the two for really small msg rates:
    act_publishers: "{{ [[ msg_rate | int, sdk_publishers] | min, 1] | max }}"
    sdk_consumers: "{{ act_publishers }}" #default number of clients on each consumer hosts - needs to match publishers!
    sdk_credentials: "-cu={{ broker_username }}@{{ broker_vpn }} -cp={{ broker_password }}"
    async_retries: "{{ runlength / 10 + 5 | round | int }}" #how long ansible is waiting for the sdks to finish (in 10s intervals).
    
    # some variables for pretty printing variables/test parameters
    filler: "            "
    str_msg_size: "{{ ([filler, msg_size] |join)[-8:] }}"
    str_overall_rate: "{{ ([filler, target_msg_rate] | join)[-8:] }}"
    str_msg_rate: "{{ ([filler, msg_rate] | join)[-8:] }}"
    str_mt: "{{ ([filler, mt] | join)[-13:] }}"
    str_fanout: "{{ ([filler, sdk_fanout] | join)[-8:] }}"
    str_parallel_hosts: "{{ ([filler, parallel_hosts] | join)[-8:] }}"
    str_publishers: "{{ ([filler, act_publishers] | join)[-8:] }}"
    
  ######################
  ######## MAIN ########
  ######################
  tasks:
  - name: 'echo_start'
    debug:
      msg:
        - "#############################################"
        - "# Target message rate              {{ str_overall_rate }} #"
        - "# Message rate per publisher host  {{ str_msg_rate }} #"
        - "# Fanout                           {{ str_fanout }} #"
        - "# Message size                     {{ str_msg_size }} #"
        - "# Message type                {{ str_mt }} #"
        - "# Parallel hosts (pub/sub)         {{ str_parallel_hosts }} #"
        - "# Parallel processes per host      {{ str_publishers }} #"
        - "#############################################"
    run_once: true
    tags: debug
  - name: 'create pubSubTools'
    file:
      path: "/home/{{ sshuser }}/pubSubTools"
      state: directory
      mode: 0755
  - name: 'copy sdkperf'
    copy:
      src: ../pubSubTools/{{ item.src }}
      dest: "{{ script_path }}/{{ item.dest }}"
      owner: "{{ sshuser }}"
      group: "{{ sshuser }}"
      mode: "u+x"
    with_items:
      - { src: LICENSES, dest: LICENSES }
      - { src: sdkperf_c, dest: sdkperf_c }
  - name: 'copy scripts'
    copy:
      src: ../scripts/{{ item.src }}
      dest: "{{ script_path }}/{{ item.dest }}"
      owner: "{{ sshuser }}"
      group: "{{ sshuser }}"
      mode: "u+x"
    with_items:
      - { src: sdkpublisher.sh, dest: sdkpublisher.sh }
      - { src: sdkconsumers.sh, dest: sdkconsumers.sh }
  - name: 'run consumer'
    shell:  "{{ script_path }}/sdkconsumers.sh {{ runlength + 10 }} {{ sdk_consumers }} {{ item.topic }} {{ sdk_fanout }} -cip={{ broker }} {{ sdk_credentials }} -cc={{ sdk_consumer_threads }} -mt={{ mt }} | tee sdk.log"
    when: "item.groups in group_names and
    ( item.index|int <= parallel_hosts )"
    async: "{{ runlength + 20 }}"
    poll: 0
    args:
      chdir: "{{ script_path }}/"
      executable: "/bin/bash"
    register: "sub"
    with_items:
      - { index: 1, topic: 'topic1', groups: 'subhost' }
  - name: 'run publishers'
    shell:  "{{ script_path }}/sdkpublisher.sh {{ runlength }} {{ msg_rate }} {{ act_publishers }} 999999999 {{ item.topic }} -cip={{ broker }} {{ sdk_credentials}} -msa={{ msg_size }} -mt={{ mt }} | tee sdk.log"
    when: "item.groups in group_names and
    ( item.index|int <= parallel_hosts )"
    async: "{{ runlength + 30 }}"
    poll: 10
    args:
      chdir: "{{ script_path }}/"
      executable: "/bin/bash"
    register: "pub"
    with_items:
      - { index: 1, topic: 'topic1', groups: 'pubhost' }

  - name: 'check publishers'
    async_status:
      jid: "{{ item.ansible_job_id }}"
    ignore_errors: True
    register: "pub_result"
    until: pub_result.finished
    retries: "{{ async_retries | int }}"
    delay: 10
    failed_when: pub_result.rc is defined and pub_result.rc != 0
    when: not item is skipped
    with_items: "{{ pub.results }}"

  - name: 'display pub results'
    debug:
      msg: "{{ item.stdout | default('(no output)') }}"
    loop: "{{ pub.results }}"
    when: not item is skipped

  - name: 'check consumers'
    async_status:
      jid: "{{ item.ansible_job_id }}"
    ignore_errors: True
    register: "sub_result"
    until: sub_result.finished
    retries: "{{ async_retries | int }}"
    delay: 10
    when: not item is skipped
    with_items: "{{ sub.results }}"
  - name: 'display sub results'
    debug:
      msg: "{{ item.stdout | default('(no output)') }}"
    loop: "{{ sub_result.results }}"
    when: not item is skipped

  - name: 'echo_end'
    debug:
      msg:
        - "#############################################"
        - "# Target message rate              {{ str_overall_rate }} #"
        - "# Message rate per publisher host  {{ str_msg_rate }} #"
        - "# Fanout                           {{ str_fanout }} #"
        - "# Message size                     {{ str_msg_size }} #"
        - "# Message type                {{ str_mt }} #"
        - "# Parallel hosts (pub/sub)         {{ str_parallel_hosts }} #"
        - "# Parallel processes per host      {{ str_publishers }} #"
        - "#############################################"
    run_once: true
